### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mpatchesny** [mpatchesny/datingApp#40]
16.04
back-end:

- [x] - implementacja założonych przypadków użycia
- [x] - endpointy API aplikacji

30.04
dokończenie back-endu:

- [x] - uwierzytelnianie użytkownika
- [x] - zdarzenia aplikacji (nowa para, nowa wiadomość)
- [x] - dodawanie zdjęć do swojego konta

14.05
front-end:

- [ ] - obsługa endpointów
- [x] - obsługa uwierzytelniania po stronie klienta
- [x] - podstawowy wygląd

04.06
dokończenie front-endu:

- [ ] - dopracowanie wyglądu

Zaległe:

- [ ] autoryzacja użytkownika
~~- [ ] - opcjonalnie: notyfikacje typu push przy określonych zdarzeniach (nowa para, nowa wiadomość)~~
